### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by brainomite** [brainomite/we-meet#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by m1010j** [comment]
Looks great! The only thing I would change is the drop down menu, which is a bit further left of the right edge of the window than on Meetup.

**Comment by brainomite** [comment]
The one issue is resolved

**Comment by brainomite** [comment]
Requested changes made:

- [x] Nav link colors

additional changes:

1. Font size and spacing pf text within the splash
2. The fact that the links change colors when logged in on the nav bar

**Comment by brainomite** [comment]
Changes are up on heroku for verification
